// <auto-generated />
using System;
using BrickDex.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrickDex.Core.Data.Migrations
{
    [DbContext(typeof(BrickDexContext))]
    [Migration("20260101140112_AddInviteSystem")]
    partial class AddInviteSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrickDex.Core.Models.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UsedByUserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableInventory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("SetNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetNum");

                    b.ToTable("RebrickableInventories", (string)null);
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableInventoryMinifig", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("FigNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId", "FigNum");

                    b.HasIndex("FigNum");

                    b.ToTable("RebrickableInventoryMinifigs", (string)null);
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableInventorySet", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("SetNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId", "SetNum");

                    b.HasIndex("SetNum");

                    b.ToTable("RebrickableInventorySets", (string)null);
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableMinifig", b =>
                {
                    b.Property<string>("FigNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NumParts")
                        .HasColumnType("int");

                    b.HasKey("FigNum");

                    b.ToTable("RebrickableMinifigs", (string)null);
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableSet", b =>
                {
                    b.Property<string>("SetNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NumParts")
                        .HasColumnType("int");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SetNum");

                    b.HasIndex("ThemeId");

                    b.ToTable("RebrickableSets", (string)null);
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableTheme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("RebrickableThemes", (string)null);
                });

            modelBuilder.Entity("BrickDex.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrickDex.Core.Models.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("BrickDex.Core.Models.UserSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsWishlist")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SetNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetNumber");

                    b.HasIndex("UserId", "SetNumber")
                        .IsUnique();

                    b.ToTable("UserSets");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Invite", b =>
                {
                    b.HasOne("BrickDex.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrickDex.Core.Models.User", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableInventory", b =>
                {
                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableSet", "Set")
                        .WithMany("Inventories")
                        .HasForeignKey("SetNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableInventoryMinifig", b =>
                {
                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableMinifig", "Minifig")
                        .WithMany("InventoryMinifigs")
                        .HasForeignKey("FigNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableInventory", "Inventory")
                        .WithMany("InventoryMinifigs")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Minifig");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableInventorySet", b =>
                {
                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableInventory", "Inventory")
                        .WithMany("InventorySets")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableSet", "Set")
                        .WithMany("InventorySets")
                        .HasForeignKey("SetNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableSet", b =>
                {
                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableTheme", "Theme")
                        .WithMany("Sets")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableTheme", b =>
                {
                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableTheme", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BrickDex.Core.Models.UserLogin", b =>
                {
                    b.HasOne("BrickDex.Core.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrickDex.Core.Models.UserSet", b =>
                {
                    b.HasOne("BrickDex.Core.Models.Rebrickable.RebrickableSet", "Set")
                        .WithMany("UserSets")
                        .HasForeignKey("SetNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrickDex.Core.Models.User", "User")
                        .WithMany("UserSets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableInventory", b =>
                {
                    b.Navigation("InventoryMinifigs");

                    b.Navigation("InventorySets");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableMinifig", b =>
                {
                    b.Navigation("InventoryMinifigs");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableSet", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventorySets");

                    b.Navigation("UserSets");
                });

            modelBuilder.Entity("BrickDex.Core.Models.Rebrickable.RebrickableTheme", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("BrickDex.Core.Models.User", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("UserSets");
                });
#pragma warning restore 612, 618
        }
    }
}
