<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Lucene.Net" />
    <PackageReference Include="Lucene.Net.Analysis.Common" />
    <PackageReference Include="Lucene.Net.Facet" />
    <PackageReference Include="Lucene.Net.QueryParser" />
    <PackageReference Include="Lucene.Net.Store.Azure" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrickDex.Core\BrickDex.Core.csproj" />
  </ItemGroup>

</Project>
