// <auto-generated />
using BrickDex.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BrickDex.Web.Data.Migrations;

[DbContext(typeof(BrickDexContext))]
[Migration("20251230152536_AddSetStatus")]
partial class AddSetStatus {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

        modelBuilder.Entity("BrickDex.Core.Models.LegoSet", b => {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT");

            b.Property<long>("CreatedAt")
                .HasColumnType("INTEGER");

            b.Property<string>("ImageUrl")
                .HasMaxLength(1024)
                .HasColumnType("TEXT");

            b.Property<bool>("IsWishlist")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("TEXT");

            b.Property<string>("Notes")
                .HasMaxLength(4096)
                .HasColumnType("TEXT");

            b.Property<int>("NumParts")
                .HasColumnType("INTEGER");

            b.Property<int>("Quantity")
                .HasColumnType("INTEGER");

            b.Property<string>("SetNumber")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("TEXT");

            b.Property<string>("SetUrl")
                .HasMaxLength(1024)
                .HasColumnType("TEXT");

            b.Property<int>("Status")
                .HasColumnType("INTEGER");

            b.Property<string>("ThemeName")
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<long>("UpdatedAt")
                .HasColumnType("INTEGER");

            b.Property<int>("Year")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("SetNumber");

            b.ToTable("LegoSets");
        });
#pragma warning restore 612, 618
    }
}
