<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>46b5049c-1d81-463f-acaa-d59310b0b0ef</UserSecretsId>
  </PropertyGroup>

  <!-- Exclude node_modules from dotnet watch -->
  <ItemGroup>
    <Watch Remove="..\BrickDex.Frontend\node_modules\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OAuth.GitHub" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Shorthand.Vite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrickDex.Core\BrickDex.Core.csproj" />
  </ItemGroup>

</Project>
